### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stringify')

### ISSUE THREAD

**Issue by Lippiece** [stylelint/postcss-css-in-js#298]
### What steps are needed to reproduce the bug?

`npm i -g stylelint postcss-syntax @stylelint/postcss-css-in-js`

.stylelintrc.json:
```
...
"customSyntax": "@stylelint/postcss-css-in-js",
...
```

test.js:
```
const css = ( {
  backgroundColor: "#f5f5f5",
  border         : "0.1em solid #555",
  color          : "white",
  content        : "Search",
  fontSize       : "1.5em",
  fontWeight     : "bold",
  height         : "2em",
  outline        : "none",
} );
```

`stylelint test.js`

### What did you expect to happen?

Stylelint to do some linting

### What actually happened?

<details>
<summary>stylelint test.js result</summary>

```
TypeError: Cannot read properties of undefined (reading 'stringify')
    at Function.stringify (/home/lippiece/.nvm/versions/node/v18.8.0/lib/node_modules/postcss-syntax/stringify.js:8:38)
    at MapGenerator.generate (/home/lippiece/.nvm/versions/node/v18.8.0/lib/node_modules/stylelint/node_modules/postcss/lib/map-generator.js:323:12)
    at LazyResult.stringify (/home/lippiece/.nvm/versions/node/v18.8.0/lib/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.runAsync (/home/lippiece/.nvm/versions/node/v18.8.0/lib/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:443:17)
    at LazyResult.async (/home/lippiece/.nvm/versions/node/v18.8.0/lib/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/lippiece/.nvm/versions/node/v18.8.0/lib/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:206:17)
```

</details>

**Comment by klarstrup** [comment]
same

**Comment by Lippiece** [comment]
@klarstrup 
My solution is to ditch this forsaken module and use [https://github.com/43081j/postcss-lit](postcss-lit) as a customSyntax. It works.

**Comment by AJ-7885** [comment]
same
