### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'stringify') #298 

### ISSUE THREAD

**Issue by awolyniec-agencyspotter** [stylelint/postcss-css-in-js#300]
### What steps are needed to reproduce the bug?

Run `stylelint --cache --cache-location node_modules/.cache/stylelint --fix --max-warnings 0`

`.stylelintrc.json`

```
...
"customSyntax": "@stylelint/postcss-css-in-js",
...
```

### What did you expect to happen?

Linting

### What actually happened?

```
TypeError: Cannot read properties of undefined (reading 'stringify')
    at Function.stringify (/Users/alecwolyniec/partner-mangement-web/node_modules/postcss-syntax/stringify.js:8:38)
    at MapGenerator.generate (/Users/alecwolyniec/partner-mangement-web/node_modules/stylelint/node_modules/postcss/lib/map-generator.js:323:12)
    at LazyResult.stringify (/Users/alecwolyniec/partner-mangement-web/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.runAsync (/Users/alecwolyniec/partner-mangement-web/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:443:17)
    at LazyResult.async (/Users/alecwolyniec/partner-mangement-web/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/alecwolyniec/partner-mangement-web/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:206:17)
```

**Comment by moisseev** [comment]
Duplicate of #298

**Comment by AJ-7885** [comment]
this is not solved and issue remind same and blocker to use, dose anybody have any solution for it.

**Comment by cstegeman** [comment]
Same here, I keep at version `14.9.1` of stylelint. Upgrading breaks it altogether like in the description

**Comment by cstegeman** [comment]
Is there any update to this issue?

**Comment by d-leb** [comment]
I was able to work around the issue using the following to my `.yarnrc.yml` file:

<pre><code>packageExtensions:
  stylelint@*:
    peerDependencies:
      "@stylelint/postcss-css-in-js": "*"
      "postcss": "*"</code></pre>

However, as Stylelint, postcss and post-css-in-js update, you may have to adjust these settings.

**Comment by d-leb** [comment]
I am assuming if you are using pnpm, there is an equivalent.

**Comment by lordprotein** [comment]
The same problem(

**Comment by hudochenkov** [comment]
Try [`postcss-styled-syntax`](https://github.com/hudochenkov/postcss-styled-syntax) if you use styled-components or something similar.

**Comment by lordprotein** [comment]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/39030827/212047930-c7662fce-542a-480e-a21d-d42020e279ad.png">

Tried that
An error occurs when I use stylelint fix

**Comment by hudochenkov** [comment]
Could you open an issue in `postcss-styled-syntax` repo with reproducible repository, please?

**Comment by lordprotein** [comment]
@hudochenkov #https://github.com/hudochenkov/postcss-styled-syntax/issues/4
